name: Deploy Walmi App

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  PM2_APP_NAME: walmi-next
  NODE_VERSION: '22' 

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Verify SSH connection
      run: |
        ssh -T -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} echo "SSH connection successful"

     
    - name: Deploy application
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
        set -e
        cd ${{ secrets.APP_DIRECTORY }}
        
        echo "1. Stopping existing application..."
        if pm2 list | grep -q "$PM2_APP_NAME"; then
          pm2 stop "$PM2_APP_NAME"
          pm2 delete "$PM2_APP_NAME"
        fi
        
        echo "2. Pulling latest changes..."
        git fetch --all
        git reset --hard origin/main
        
        echo "3. Installing dependencies..."
        npm ci --prefer-offline
        
        echo "4. Building application..."
        npm run build
        
        echo "5. Starting application..."
        pm2 start npm --name "$PM2_APP_NAME" -- start
        
        echo "6. Saving PM2 process list..."
        pm2 save
        pm2 startup 2>&1 | grep -v "\[PM2\]" || true
        EOF
