name: Deploy Walmi Next App

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    
    # Шаг 1: Настроим SSH-ключи и доступ
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # Шаг 2: Остановка приложения на сервере
    - name: Stop application with PM2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} "pm2 stop ${PM2_APP_NAME} || true" 
    
    # Шаг 3: Получение последних изменений на сервер
    - name: Pull latest code from Git repository
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} "cd ${{ secrets.DIRECTORY_PATH }} && git pull origin main"
    
    # Шаг 4: Установка зависимостей
    - name: Install dependencies
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} "cd ${{ secrets.DIRECTORY_PATH }} && npm install"
    
    # Шаг 5: Билд проекта
    - name: Build the project
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} "cd ${{ secrets.DIRECTORY_PATH }} && npm run build"
    
    # Шаг 6: Запуск приложения с PM2
    - name: Start application with PM2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} "cd ${{ secrets.DIRECTORY_PATH }} && pm2 start npm --name ${PM2_APP_NAME} -- start"
