name: Deploy Walmi Next.js App

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  PM2_APP_NAME: walmi-next
  GIT_REPO: https://github.com/Neon3341/walmi-next.git

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Configure SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Verify SSH connection
      run: |
        ssh -T -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} echo "SSH connection successful"

    - name: Deploy application
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
        set -e 
        
        if [ ! -d "${{ secrets.APP_DIRECTORY }}" ]; then
          echo "Creating application directory..."
          mkdir -p "${{ secrets.APP_DIRECTORY }}"
        fi
    
        cd "${{ secrets.APP_DIRECTORY }}"
    
        echo "Stopping existing application..."
        pm2 stop "$PM2_APP_NAME" || true
        
        echo "Checking git repository..."
        if [ ! -d .git ]; then
          echo "Initializing git repository..."
          git init
          git remote add origin $GIT_REPO
          git fetch
          git checkout -t origin/main || git checkout main
        else
          echo "Existing git repository found"
        fi
    
        echo "Pulling latest changes..."
        git reset --hard
        git clean -fd
        git pull origin main
    
        echo "Installing dependencies..."
        npm ci --prefer-offline
        
        echo "Building application..."
        npm run build
    
        echo "Starting application..."
        pm2 start npm --name "$PM2_APP_NAME" -- start
    
        echo "Saving PM2 process list..."
        pm2 save
        EOF
