name: Deploy WalmiNext App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # Add known hosts first to avoid strict host checking
    - name: Add server to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

    # Test SSH connection first
    - name: Test SSH connection
      run: ssh ${{ secrets.USER }}@${{ secrets.HOST }} "echo 'SSH connection successful!'"

    # Set environment variable for PM2 app name
    - name: Set PM2 app name
      run: echo "PM2_APP_NAME=${{ secrets.PM2_APP_NAME }}" >> $GITHUB_ENV

    # Then proceed with your deployment steps
    - name: Stop application with PM2
      run: ssh ${{ secrets.USER }}@${{ secrets.HOST }} "pm2 stop $PM2_APP_NAME || true"
    
    - name: Pull latest code
      run: ssh ${{ secrets.USER }}@${{ secrets.HOST }} "cd ${{ secrets.DIRECTORY_PATH }} && git pull origin main"
    
    - name: Install dependencies
      run: ssh ${{ secrets.USER }}@${{ secrets.HOST }} "cd ${{ secrets.DIRECTORY_PATH }} && npm install"
    
    - name: Build the project
      run: ssh ${{ secrets.USER }}@${{ secrets.HOST }} "cd ${{ secrets.DIRECTORY_PATH }} && npm run build"
    
    - name: Start application with PM2
      run: ssh ${{ secrets.USER }}@${{ secrets.HOST }} "cd ${{ secrets.DIRECTORY_PATH }} && pm2 start npm --name $PM2_APP_NAME -- start"
